# Generated by Django 4.0.5 on 2022-06-05 23:32

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_author_image_alter_topic_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tred',
            name='comments',
        ),
        migrations.AddField(
            model_name='tred',
            name='title',
            field=models.CharField(default='Tred', max_length=40),
        ),
        migrations.AlterField(
            model_name='tred',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=100, size=[1280, 720], upload_to='treds'),
        ),
    ]
