# Generated by Django 4.0.5 on 2022-06-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_tred_comments_tred_title_alter_tred_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tred',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
