# Generated by Django 4.0.5 on 2022-06-06 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tred_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tred',
        ),
    ]
