# Generated by Django 4.0.5 on 2022-06-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_reply_comment_tred_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='tred',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
