# Generated by Django 4.0.5 on 2022-06-05 18:16

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_tred_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tred',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=100, size=[1280, 720], upload_to='images'),
        ),
    ]
