# Generated by Django 4.0.5 on 2022-06-06 00:29

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_tred'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Tred', max_length=40)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=100, size=[1280, 720], upload_to='treds')),
                ('content', models.TextField(default='This tred is empty :(', max_length=10000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.author')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.topic')),
            ],
        ),
    ]
