# Generated by Django 4.0.5 on 2022-06-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_tred'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'comments'},
        ),
    ]
