# Generated by Django 4.0.5 on 2022-06-06 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_comment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tred',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tred',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.DeleteModel(
            name='Tred',
        ),
    ]
