# Generated by Django 4.0.5 on 2022-06-06 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_comment_tred_reply_comment_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tred',
            name='topics',
        ),
        migrations.AddField(
            model_name='tred',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.topic'),
        ),
    ]
