# Generated by Django 4.0.5 on 2022-06-06 13:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_author_slug_alter_topic_slug_alter_tred_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='role',
            field=models.CharField(default='Member', max_length=40),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(default=uuid.UUID('7918578e-e40a-483b-980b-7eca76a32b8c'), max_length=200),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default=uuid.UUID('936863a9-1c13-49e2-85ef-f7008c88a184'), max_length=200),
        ),
        migrations.AlterField(
            model_name='tred',
            name='slug',
            field=models.SlugField(default=uuid.UUID('cd9b0272-769d-4a29-9bf6-18fa9ebe7846'), max_length=200),
        ),
    ]
