# Generated by Django 4.0.5 on 2022-06-06 16:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_author_role_alter_author_slug_alter_topic_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(default=uuid.UUID('840bba68-48aa-4dd8-bd60-30eb464b9bbd'), max_length=200),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default=uuid.UUID('0e2f433d-11a1-48bb-b5d5-4b71ca82d85d'), max_length=200),
        ),
        migrations.AlterField(
            model_name='tred',
            name='slug',
            field=models.SlugField(default=uuid.UUID('efe798ed-da1e-41b5-b656-30fa2eddf150'), max_length=200),
        ),
    ]
