# Generated by Django 4.0.5 on 2022-06-06 21:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_topic_approved_alter_author_slug_alter_topic_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(default=uuid.UUID('09e168c0-8051-4e0d-b646-2aea759842ad'), max_length=200),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default=uuid.UUID('6337ae9d-3528-45bf-9675-e5b7108c4d4d'), max_length=200),
        ),
        migrations.AlterField(
            model_name='tred',
            name='slug',
            field=models.SlugField(default=uuid.UUID('86a35fbf-9a96-43f4-9bc2-23f3b793f2c2'), max_length=200),
        ),
    ]
