# Generated by Django 4.0.5 on 2022-06-09 23:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_author_slug_alter_topic_slug_alter_tred_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(default=uuid.UUID('9b93e2b2-0ff1-4f94-ab02-ce0d8b10fad1'), max_length=200),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default=uuid.UUID('fca367fe-1dde-4d4d-847c-6468763d627d'), max_length=200),
        ),
        migrations.AlterField(
            model_name='tred',
            name='slug',
            field=models.SlugField(default=uuid.UUID('26299ed7-ca7f-408a-884b-f358769847cf'), max_length=200),
        ),
    ]
