# Generated by Django 4.0.5 on 2022-06-13 00:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_author_slug_alter_topic_slug_alter_tred_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tred',
            name='image',
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(default=uuid.UUID('c135f3d9-bc39-4630-a0e2-79d968ed0316'), max_length=200),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default=uuid.UUID('b7e83c7b-53ad-48fe-8765-7804da418e5f'), max_length=200),
        ),
        migrations.AlterField(
            model_name='tred',
            name='slug',
            field=models.SlugField(default=uuid.UUID('aae107c6-7ffb-4cb8-b405-51f0512527c4'), max_length=200),
        ),
    ]
